server.port=8080
spring.application.name=climalert-service
spring.threads.virtual.enabled=true

weather.api.url=https://api.weatherapi.com/v1/current.json
weather.api.key=API_KEY_WEATHER
weather.api.location=Buenos Aires, Argentina