server.port=8080
spring.application.name=climalert-service
spring.threads.virtual.enabled=true

weather.api.url=https://api.weatherapi.com/v1/current.json
weather.api.key=${WEATHER_API_KEY:API_KEY_WEATHER}
weather.api.location=${WEATHER_API_LOCATION:Buenos Aires, Argentina}

climalert.storage.clima-file=data/clima-registros.json
climalert.storage.alerta-file=data/alertas.json

climalert.scheduling.enabled=true
climalert.scheduling.weather.fixed-rate-ms=300000
climalert.scheduling.weather.initial-delay-ms=10000
climalert.scheduling.alert.fixed-rate-ms=60000
climalert.scheduling.alert.initial-delay-ms=20000

climalert.mail.enabled=false
climalert.mail.from=${CLIMALERT_MAIL_FROM:no-reply@climalert.local}
climalert.mail.recipients=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

spring.mail.host=${SPRING_MAIL_HOST:}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_SMTP_STARTTLS:true}
